services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: super-app
        container_name: super-app
        ports:
            - "1000:80"
        volumes:
            - ./:/var/www/html
            - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
        working_dir: /var/www/html
        networks:
            - mysql-net

networks:
    mysql-net:
        external: true
